// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx4XNy-c0Rql5K-s0xrY7g1jeY_92bXYQ',
    appId: '1:1023108112917:web:79d2be6b1e46f02b0ce41c',
    messagingSenderId: '1023108112917',
    projectId: 'receipe-app-7de62',
    authDomain: 'receipe-app-7de62.firebaseapp.com',
    storageBucket: 'receipe-app-7de62.firebasestorage.app',
    measurementId: 'G-HNE8RLX7P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYBWNSAFlLELUMgeealfpvkAZ-1NCR9wY',
    appId: '1:1023108112917:android:63d8c884c69201c90ce41c',
    messagingSenderId: '1023108112917',
    projectId: 'receipe-app-7de62',
    storageBucket: 'receipe-app-7de62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXOjF_V4FNNuQEj2aHn-kEgIos6v1Sbl4',
    appId: '1:1023108112917:ios:c866779f751fbb0f0ce41c',
    messagingSenderId: '1023108112917',
    projectId: 'receipe-app-7de62',
    storageBucket: 'receipe-app-7de62.firebasestorage.app',
    iosBundleId: 'com.example.receipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXOjF_V4FNNuQEj2aHn-kEgIos6v1Sbl4',
    appId: '1:1023108112917:ios:c866779f751fbb0f0ce41c',
    messagingSenderId: '1023108112917',
    projectId: 'receipe-app-7de62',
    storageBucket: 'receipe-app-7de62.firebasestorage.app',
    iosBundleId: 'com.example.receipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx4XNy-c0Rql5K-s0xrY7g1jeY_92bXYQ',
    appId: '1:1023108112917:web:bcf7338b0427e2c90ce41c',
    messagingSenderId: '1023108112917',
    projectId: 'receipe-app-7de62',
    authDomain: 'receipe-app-7de62.firebaseapp.com',
    storageBucket: 'receipe-app-7de62.firebasestorage.app',
    measurementId: 'G-KJ09XTD5EF',
  );
}
